/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testventanas;


import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Jonathan Jané
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.lblOcultar.setVisible(false); //inicializa en falso el ojo
        
        //setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        //para poner la ventana en el centro
        this.setLocationRelativeTo(null);
        //mostrar_logo();
    }
    
    
    //ADITION METHOD
    /*private void mostrar_logo(){
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/img/icono.png"));
    Image imagen = icono.getImage();
    ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(75,75,Image.SCALE_SMOOTH));
    //lblLogo.setIcon(iconoEscalado);
}*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIfoUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblVer = new javax.swing.JLabel();
        lblOcultar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO_DE_SESION");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIfoUsuario.setBackground(new java.awt.Color(235, 235, 235));
        pnlIfoUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Light", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Iniciar Sesión");
        pnlIfoUsuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, 40));

        jLabel2.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        jLabel2.setText("CORREO ELECTRÓNICO");
        pnlIfoUsuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        jLabel3.setText("CONTRASEÑA");
        pnlIfoUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(191, 17, 145));
        btnIngresar.setForeground(new java.awt.Color(234, 234, 234));
        btnIngresar.setText("INGRESAR");
        btnIngresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        pnlIfoUsuario.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 120, 30));

        jTextField1.setBackground(new java.awt.Color(234, 234, 234));
        jTextField1.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(191, 17, 139));
        jTextField1.setText("  ");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pnlIfoUsuario.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 280, 30));

        txtContra.setBackground(new java.awt.Color(234, 234, 234));
        txtContra.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        txtContra.setForeground(new java.awt.Color(191, 17, 139));
        txtContra.setBorder(null);
        pnlIfoUsuario.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 240, 30));

        jSeparator1.setForeground(new java.awt.Color(191, 17, 145));
        pnlIfoUsuario.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 330, 10));

        jSeparator2.setForeground(new java.awt.Color(191, 17, 145));
        pnlIfoUsuario.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 330, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-bloquear-40.png"))); // NOI18N
        pnlIfoUsuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 40, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-email-40.png"))); // NOI18N
        pnlIfoUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 40, 50));

        jButton2.setBackground(new java.awt.Color(234, 234, 234));
        jButton2.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(191, 17, 145));
        jButton2.setText("Crear cuenta nueva");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlIfoUsuario.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 140, 30));

        lblVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ver-24.png"))); // NOI18N
        lblVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerMouseClicked(evt);
            }
        });
        pnlIfoUsuario.add(lblVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 30, 40));

        lblOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ocultar-24.png"))); // NOI18N
        lblOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOcultarMouseClicked(evt);
            }
        });
        pnlIfoUsuario.add(lblOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 30, 40));

        jButton1.setBackground(new java.awt.Color(234, 234, 234));
        jButton1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(191, 17, 145));
        jButton1.setText("Ingresar como estudiante");
        jButton1.setBorder(null);
        pnlIfoUsuario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 150, 30));

        getContentPane().add(pnlIfoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 390, 490));

        jPanel1.setBackground(new java.awt.Color(191, 17, 145));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(191, 17, 145));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(235, 235, 235));
        jLabel7.setText("ReserV");
        jPanel2.add(jLabel7);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 240, 60));

        jPanel4.setBackground(new java.awt.Color(239, 239, 239));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(191, 17, 145));
        jLabel8.setText("+");
        jPanel4.add(jLabel8);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 90, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jona.png"))); // NOI18N
        jLabel6.setText(" ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 360));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(235, 235, 235));
        jLabel9.setText("tus eventos.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, 20));

        jLabel10.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(235, 235, 235));
        jLabel10.setText("La mejor manera de gestionar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void lblVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerMouseClicked
    
        //Evento para hacer visible la contraseña x medio de la label ojo
        lblVer.setVisible(false); 
        lblOcultar.setVisible(true);
        txtContra.setEchoChar((char)0);
    }//GEN-LAST:event_lblVerMouseClicked

    private void lblOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOcultarMouseClicked
        
        //Evento para ocultar la contra ojo
        lblVer.setVisible(true);
        lblOcultar.setVisible(false);
        txtContra.setEchoChar('●');
        
    }//GEN-LAST:event_lblOcultarMouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       
        frmMenu frmMenu = new frmMenu();
        frmMenu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblOcultar;
    private javax.swing.JLabel lblVer;
    private javax.swing.JPanel pnlIfoUsuario;
    private javax.swing.JPasswordField txtContra;
    // End of variables declaration//GEN-END:variables
}
